(* ::Package:: *)

(* ::Input:: *)
(*(*Reset the simulation and create the initial population.*)*)
(**)
(*initialize[percTotl_,percPartial_]:=(maxtimeslot=180*DAYS;*)
(**)
(*(*Clear data from the previous run.*)*)
(*Do[dsStTraject[state]["DropAll"];dsIDList[state]["DropAll"];,{state,SUSCEPTIBLE,DEAD}];*)
(**)
(*dsAgTraject["DropAll"];*)
(**)
(*dsBuffer["DropAll"];*)
(**)
(*memoMat=Table[0,{x,1,XSIZE},{y,1,YSIZE}];*)
(**)
(*locTrj={};*)
(**)
(*timeslot=1;*)
(**)
(**)
(*(*Calculate dose counts and vaccination group sizes.*)*)
(*numTotlDoses=Floor[percTotl*POPULATION/100];*)
(**)
(*numAgnPartVaxed=Floor[percPartial*POPULATION/100];*)
(**)
(*numAgnFullVaxed=Floor[(numTotlDoses-numAgnPartVaxed)/2];*)
(**)
(**)
(*(*Sample how many agents develop sheild by vaccination.*)*)
(*numAgnPartShld=Floor[RandomVariate[BinomialDistribution[numAgnPartVaxed,\[Pi]1]]];*)
(**)
(*numAgnFullShld=Floor[RandomVariate[BinomialDistribution[numAgnFullVaxed,\[Pi]2]]];*)
(**)
(**)
(*(*Select initial exposed agents and protection groups.*)*)
(*initNumExpo=Ceiling[initRateExposed*POPULATION];*)
(**)
(*initNumSusc=POPULATION-initNumExpo;*)
(**)
(*initAgnExpoList=RandomSample[Range[POPULATION],initNumExpo];*)
(**)
(*Scan[dsIDList[SUSCEPTIBLE]["Push",#]&,Complement[Range[POPULATION],initAgnExpoList]];*)
(**)
(*initAgnPartShldList=RandomSample[Range[POPULATION],numAgnPartShld];*)
(**)
(*initAgnFullShldList=RandomSample[Complement[Range[POPULATION],initAgnPartShldList],numAgnFullShld];*)
(**)
(**)
(*(*Track agents whose protection is still developing.*)*)
(*agCreatingShldList={};*)
(**)
(**)
(*(*Assign each agent an initial state,timer,and position.*)Do[Block[{cstate,nstate,shlv,timer,xpos,ypos},cstate=SUSCEPTIBLE;*)
(*nstate=SUSCEPTIBLE;*)
(*shlv=NONE;*)
(*timer=\[Infinity];*)
(*xpos=RandomChoice[Range[XSIZE]];*)
(*ypos=RandomChoice[Range[YSIZE]];*)
(*Which[MemberQ[initAgnPartShldList,id],nstate=PROTECTED;shlv=PARTIAL;timer=tau11;*)
(*AppendTo[agCreatingShldList,{id,timer}],MemberQ[initAgnFullShldList,id],nstate=PROTECTED;shlv=FULL;timer=tau21;*)
(*AppendTo[agCreatingShldList,{id,timer}]];*)
(*Which[MemberQ[initAgnExpoList,id],cstate=EXPOSED];*)
(*agList[[id]]={id,cstate,nstate,shlv,timer,xpos,ypos}],{id,1,POPULATION}];*)
(**)
(*(*Set initial infectious counts and schedule exposed agents.*)(memoMat[[agList[[#]][[XPOS]],agList[[#]][[YPOS]]]]+=1)&/@initAgnExpoList;*)
(*setNext[timeslot]/@initAgnExpoList;*)
(**)
(*(*Move buffered agents into their state collections.*)dsIDList[agList[[#]][[CSTATE]]]["Push",#]&/@Normal[dsBuffer];*)
(*dsBuffer["DropAll"];*)
(**)
(*(*Save initial state counts and the first agent snapshot.*)Do[dsStTraject[state]["Push",dsIDList[state]["Length"]],{state,SUSCEPTIBLE,DEAD}];*)
(*dsAgTraject["Push",agList];*)
(*);*)
